wpsblog/wpsblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from wpsblog.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', home, name="home"),
    url(r'^about/us/$', about, name="about"),
    url(r'^rooms/(?P<room_id>\d+)/$', room, name="room"),
    url(r'^news/$', news, name="news"),

    url(r'^policy/', include([
        url(r'terms/$', terms, name="terms"),
        url(r'privacy/$', privacy, name="privacy"),
        url(r'disclaimer/$', disclaimer, name="disclaimer"),
    ], namespace="policy")),
]

wpsblog/wpsblog/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Post(models.Model):
    title = models.CharField(
        max_length=120,
    )
    content = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "post_id": self.id,
            }
        )

    def get_update_url(self):
        return reverse(
            "posts:update",
            kwargs={
                "post_id": self.id,
            }
        )


class NaverPost(models.Model):

    keyword = models.CharField(
        max_length=16,
    )
    title = models.CharField(
        max_length=256,
    )
    content = models.TextField()
    thumbnail_image_url = models.URLField()
    original_url = models.URLField()

    def __str__(self):
        return self.title

wpsblog/wpsblog/models/comment.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class Comment(models.Model):

    user = models.ForeignKey(User)
    post = models.ForeignKey("Post")

    content = models.TextField()

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "pk": self.post.id,
            },
        ) + "#comment-" + str(self.id)

wpsblog/wpsblog/models/naver_post.py
from django.db import models


class NaverPost(models.Model):

    keyword = models.CharField(
        max_length=16,
    )
    title = models.CharField(
        max_length=256,
    )
    content = models.TextField()
    thumbnail_image_url = models.URLField()
    original_url = models.URLField()

    def __str__(self):
        return self.title

wpsblog/wpsblog/models/post.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class PostManager(models.Manager):

    def public(self):
        return self.filter(is_public=True)


class Post(models.Model):

    objects = PostManager()

    user = models.ForeignKey(User)

    title = models.CharField(
        max_length=120,
    )
    content = models.TextField()
    image = models.ImageField(
        blank=True,
        null=True,
    )
    is_public = models.BooleanField(
        default=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "pk": self.id,
            }
        )

    def get_update_url(self):
        return reverse(
            "posts:update",
            kwargs={
                "post_id": self.id,
            }
        )

    def get_image_url(self):
        if self.image:
            return self.image.url
        return "http://placehold.it/300x200"

wpsblog/wpsblog/controller.py
from django.http.response import HttpResponse


def home(request):
    return HttpResponse("hello world")


def room(request, room_id):
    return HttpResponse("This is a room detail " + room_id)

wpsblog/wpsblog/views.py
import json
import requests

from django.http.response import HttpResponse
from django.shortcuts import render


def home(request):
    return render(
        request,
        "home.html",
        {"site_name": "wps blog"},
    )


def room(request, room_id):
    url = "https://api.zigbang.com/v1/items?detail=true&item_ids=" + room_id
    response = requests.get(url)
    return HttpResponse(
        response.content,
        content_type="application/json",
    )


def news(request):
    search = request.GET.get("search")

    response = requests.get("https://watcha.net/home/news.json?page=1&per=50")
    news_dict = json.loads(response.text)
    news_list = news_dict.get("news")

    if search:
        news_list = list(filter(
            lambda news: search in news.get('title'),
            news_list,
        ))

    return render(
        request,
        "news.html",
        {"news_list": news_list},
    )

wpsblog/wpsblog/views/about.py
from django.shortcuts import render


def about(request):
    return render(
        request,
        "about.html",
        {},
    )

wpsblog/wpsblog/views/home.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        context["site_name"] = "wps blog"
        return context

wpsblog/wpsblog/views/naver_posts.py
from django.shortcuts import render

from wpsblog.models import NaverPost


def naver_posts_list(request):
    keyword = request.GET.get("keyword")
    query = request.GET.get("query")
    naver_posts = NaverPost.objects.all()

    if keyword:
        naver_posts = naver_posts.filter(keyword=keyword)

    if query:
        naver_posts = naver_posts.filter(title__contains=query)

    return render(
        request,
        "naver_posts/list.html",
        {
            "keyword": keyword,
            "query": query,
            "naver_posts": naver_posts,
        },
    )

wpsblog/wpsblog/views/news.py
import json
import requests

from django.shortcuts import render


def news(request):
    search = request.GET.get("search")

    response = requests.get("https://watcha.net/home/news.json?page=1&per=50")
    news_dict = json.loads(response.text)
    news_list = news_dict.get("news")

    if search:
        news_list = list(filter(
            lambda news: search in news.get('title'),
            news_list,
        ))

    return render(
        request,
        "news.html",
        {"news_list": news_list},
    )

wpsblog/wpsblog/views/policy.py
from django.shortcuts import render


def terms(request):
    return render(
        request,
        "policy/terms.html",
        {},
    )


def privacy(request):
    return render(
        request,
        "policy/privacy.html",
        {},
    )


def disclaimer(request):
    return render(
        request,
        "policy/disclaimer.html",
        {},
    )

wpsblog/wpsblog/views/pricing.py
from django.views.generic import View
from django.http.response import HttpResponse


class PricingView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse("Pricing Table")

wpsblog/wpsblog/views/room.py
import requests

from django.http.response import HttpResponse


def room(request, room_id):
    url = "https://api.zigbang.com/v1/items?detail=true&item_ids=" + room_id
    response = requests.get(url)
    return HttpResponse(
        response.content,
        content_type="application/json",
    )

wpsblog/wpsblog/templates/about.html
{% extends "base.html" %}


{% block content %}
<h1>About</h1>
<p>This is about fastcampus blog page</p>
{% endblock %}

wpsblog/wpsblog/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static "css/application.css" %}">
  <script src="{% static "js/application.js" %}"></script>
</head>
<body>
  {% include "header.html" %}
  {% block content %}
  {% endblock %}
  {% include "footer.html" %}
</body>

wpsblog/wpsblog/templates/footer.html
<footer>
  <h1>Footer</h1>

  <ul>
    <li><a href="{% url "policy:terms" %}">서비스 이용약관</a></li>
    <li><a href="{% url "policy:privacy" %}">개인정보 보호정책</a></li>
    <li><a href="{% url "policy:disclaimer" %}">법적고지와 책임의 한계</a></li>
  </ul>
</footer>

wpsblog/wpsblog/templates/header.html
<header>
  <h1>Header</h1>
  <ul>
    <li><a href="{% url "home" %}">Home</a></li>
    <li><a href="{% url "about" %}">About</a></li>
    <li><a href="{% url "news" %}">News</a></li>

    {% if request.user.is_authenticated %}
      <li><a href="{% url "auth:mypage" %}">{{ request.user.username }}</a></li>
      <li><a href="{% url "auth:logout" %}">Logout</a></li>
    {% else %}
      <li><a href="{% url "auth:login" %}">Login</a></li>
      <li><a href="{% url "auth:signup" %}">Signup</a></li>
    {% endif %}
  </ul>
</header>

wpsblog/wpsblog/templates/home.html
{% extends "base.html" %}


{% block title %}Home{% endblock %}

{% block content %}
  <h1>Home</h1>
  <p>{{ site_name }} 에 방문해주셔서 감사합니다.</p>
{% endblock %}

wpsblog/wpsblog/templates/news.html
{% extends "base.html" %}


{% block title %}News{% endblock %}


{% block content %}
  <h1>News</h1>
  <p>This is movie news</p>
  <p>{{ news_list|length }} 개의 영화 정보가 표시됩니다.</p>


  <ul>
    {% for news in news_list %}
      <li>
        <h2>{{ news.title }}</h2>
        <p>{{ news.content }}</p>
        <img src="{{ news.image }}"/>
      </li>
    {% endfor %}
  </ul>
{% endblock %}